backend:
  name: git-gateway
  branch: master

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: post
    label: Post
    folder: content/posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
